#!/usr/bin/env python
#-*- coding: utf8 -*-
# MuninEtherway - Simple plugin for Munin Monitoring

# Copyright © 2012 Denis 'Saymon21' Khabarov
# E-Mail: saymon at hub21 dot ru (saymon@hub21.ru)

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


'''
Config for /etc/munin/plugin-conf.d/munin-node:

[etherway]
	env.ETHERWAY_USER pUSERID
	env.ETHERWAY_PASSW mysuperpassword
'''

import etherway
from os import getenv
from sys import argv

def main():
	if len(argv) == 2 and argv[1] == 'config':
		print('graph_title Etherway Balance')
		print('graph_args --base 1024 -r')
		print('graph_category network')
		print('graph_info This graph shows the number of balance on etherway.ru for user %s.' %(getenv('ETHERWAY_USER')))
		print('RUB.label RUB')
		print('RUB.type GAUGE')
		print('RUB.info RUB')
		exit()
	else:
		value = 0
		lk=etherway.EtherwayBalanceFetcher(login=getenv('ETHERWAY_USER'), password=getenv('ETHERWAY_PASSW'))
		try:
			mybalance = lk.get_balance()
		except etherway.QueryError:
			print('RUB.value 0')
			exit()
		value = mybalance[0].split(".")
		value = int(value[0])
		print('RUB.value %d' % value)
	
if __name__ == "__main__":
	main()
